language: java

jdk:
  - openjdk8

branches:
  only:
    - master
    - /v\d+.\d+.\d+/

deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file: target/*.war
  skip_cleanup: true
  on:
    repo: michaelneu/gorillamail
    tags: true
